# Generated by Django 4.2.28 on 2026-02-10 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cliniko_api_key', models.CharField(blank=True, max_length=255)),
                ('cliniko_shard', models.CharField(default='api', max_length=50)),
                ('last_cliniko_sync', models.DateTimeField(blank=True, null=True)),
                ('last_sync_cursor', models.CharField(blank=True, max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliniko_id', models.CharField(db_index=True, max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sms_consent', models.BooleanField(default=False)),
                ('email_consent', models.BooleanField(default=False)),
                ('call_recording_consent', models.BooleanField(default=False)),
                ('first_appointment_date', models.DateField(blank=True, null=True)),
                ('last_appointment_date', models.DateField(blank=True, null=True)),
                ('first_paid_invoice_date', models.DateField(blank=True, null=True)),
                ('cliniko_created_at', models.DateTimeField(blank=True, null=True)),
                ('cliniko_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='core.clinic')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('clinic', 'cliniko_id')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('read', 'Read'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('object_repr', models.CharField(max_length=255)),
                ('changes_json', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.clinic')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribution_type', models.CharField(choices=[('call', 'Phone Call'), ('marketing_touch', 'Marketing Touch'), ('manual', 'Manual Entry'), ('unknown', 'Unknown')], max_length=20)),
                ('status', models.CharField(choices=[('auto', 'Auto-attributed'), ('manual', 'Manually Overridden'), ('pending', 'Pending Review')], default='auto', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=255)),
                ('campaign_source', models.CharField(blank=True, max_length=100)),
                ('campaign_medium', models.CharField(blank=True, max_length=100)),
                ('evidence_json', models.JSONField(default=dict)),
                ('first_invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('first_invoice_date', models.DateField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='core.clinic')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribution_overrides', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attribution', to='core.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliniko_id', models.CharField(db_index=True, max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cliniko_created_at', models.DateTimeField(blank=True, null=True)),
                ('cliniko_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.patient')),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('clinic', 'cliniko_id')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliniko_id', models.CharField(db_index=True, max_length=100)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('appointment_type', models.CharField(blank=True, max_length=100)),
                ('practitioner_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('cliniko_created_at', models.DateTimeField(blank=True, null=True)),
                ('cliniko_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.patient')),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'unique_together': {('clinic', 'cliniko_id')},
            },
        ),
    ]
