# Generated by Django 4.2.28 on 2026-02-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('new_patients', models.PositiveIntegerField(default=0)),
                ('total_patients', models.PositiveIntegerField(default=0)),
                ('appointments_scheduled', models.PositiveIntegerField(default=0)),
                ('appointments_completed', models.PositiveIntegerField(default=0)),
                ('appointments_cancelled', models.PositiveIntegerField(default=0)),
                ('appointments_no_show', models.PositiveIntegerField(default=0)),
                ('revenue_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue_from_new_patients', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ad_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_per_new_patient', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_calls', models.PositiveIntegerField(default=0)),
                ('missed_calls', models.PositiveIntegerField(default=0)),
                ('calls_converted', models.PositiveIntegerField(default=0)),
                ('tasks_created', models.PositiveIntegerField(default=0)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily metrics',
                'ordering': ['-date'],
            },
        ),
    ]
