# Generated by Django 4.2.28 on 2026-02-10 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetrics',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='core.clinic'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymetrics',
            unique_together={('clinic', 'date')},
        ),
    ]
