# Generated by Django 4.2.28 on 2026-02-10 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('google_ads', 'Google Ads'), ('meta_ads', 'Meta Ads'), ('manual', 'Manual Entry')], max_length=50)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_impressions', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('total_conversions', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tracking_phone', models.CharField(blank=True, max_length=50)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.clinic')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
                'unique_together': {('clinic', 'source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='MarketingTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, db_index=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=255)),
                ('utm_term', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('gclid', models.CharField(blank=True, db_index=True, max_length=255)),
                ('fbclid', models.CharField(blank=True, db_index=True, max_length=255)),
                ('landing_page', models.URLField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('source', models.CharField(default='ga4', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_touches', to='core.clinic')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('parent_call_sid', models.CharField(blank=True, max_length=100)),
                ('caller_phone', models.CharField(db_index=True, max_length=50)),
                ('called_phone', models.CharField(db_index=True, max_length=50)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=20)),
                ('status', models.CharField(choices=[('ringing', 'Ringing'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('busy', 'Busy'), ('no-answer', 'No Answer'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='ringing', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('campaign_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('campaign_name', models.CharField(blank=True, max_length=255)),
                ('tracking_number', models.CharField(blank=True, max_length=50)),
                ('recording_url', models.URLField(blank=True)),
                ('recording_duration', models.PositiveIntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
                ('resulted_in_appointment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_events', to='core.clinic')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('google_ads', 'Google Ads'), ('google_analytics', 'Google Analytics 4'), ('meta_ads', 'Meta Ads'), ('twilio', 'Twilio')], max_length=50)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('config_json', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='core.clinic')),
            ],
            options={
                'unique_together': {('clinic', 'integration_type')},
            },
        ),
        migrations.CreateModel(
            name='CampaignDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='integrations.campaign')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
